// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqfvleidiwpfsrmgkfpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZnZsZWlkaXdwZnNybWdrZnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDI1MzgsImV4cCI6MjA3MTIxODUzOH0.gVJtKS1969wl0mDrsIVUGzCB3Gr6Dv6VeIZBIl3yAyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});